env:
  browser: true
  node: true

parserOptions:
  parser: babel-eslint
  sourceType: module
  ecmaVersion: 2020

extends:
  - eslint:recommended
  # 规则越通用位置越在前
  - prettier
  - plugin:prettier/recommended

plugins:
  - prettier

rules:
  no-console: 1
  no-debugger: 1
  no-var: 2
  no-unused-vars: 2
  eqeqeq: 2
  no-cond-assign: 2
  no-undef: 2
  prettier/prettier: 2
